# Generated by Django 5.1.3 on 2024-12-01 13:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('scooters', '0001_initial'),
        ('users', '0005_userprofile'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('payment_status', models.BooleanField(default=False)),
                ('total_price', models.IntegerField(blank=True, null=True)),
                ('scooter_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='scooters.scooter')),
                ('userprofile_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.userprofile')),
            ],
        ),
    ]
