# Generated by Django 5.1.3 on 2024-12-02 11:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='reservation',
            old_name='scooter_id',
            new_name='scooter',
        ),
        migrations.RenameField(
            model_name='reservation',
            old_name='userprofile_id',
            new_name='userprofile',
        ),
    ]
