# Generated by Django 5.1.3 on 2024-12-03 09:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0003_alter_reservation_scooter_and_more'),
        ('scooters', '0001_initial'),
        ('users', '0006_customuser_groups_customuser_user_permissions'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservation',
            name='scooter',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='scooters.scooter'),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='userprofile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.userprofile'),
        ),
    ]
