# Generated by Django 5.1.4 on 2025-03-10 07:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0003_reservation_stripe_payment_intent_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='stripe_checkout_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
